- name: DEBIAN | Add repository
  apt_repository:
    repo: "ppa:ansible/ansible"
    state: present
  tags:
    - ansible_pull
    - packages
    - apt

- name: DEBIAN | Install needed packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop: "{{ ansible_pull_packages }}"
  tags:
    - ansible_pull
    - packages
    - apt
