- name: RHEL | Install needed packages
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: epel-testing
  loop: "{{ ansible_pull_packages }}"
  tags:
    - ansible_pull
    - packages
    - yum
